// app/(student)/ielts/_components/hubTexts.ts
// Trilingual copy for the student IELTS hub (docs/IELTS.md → "Route map / Student").
// One dictionary shared by page.tsx and the three tab components so a label is
// never re-declared per file.

import { BookOpen, Headphones, Mic, PenLine } from 'lucide-react';
import type { IeltsSkill } from '@/lib/ielts/types';

/** Hub tab keys — also the `?tab=` URL contract. */
export type HubTab = 'groups' | 'practice' | 'progress';
export const HUB_TABS: readonly HubTab[] = ['groups', 'practice', 'progress'] as const;
export const SKILL_KEYS: readonly IeltsSkill[] = ['reading', 'listening', 'writing', 'speaking'] as const;

/** Skill → icon, in the fixed hub order (reading first, as in the library). */
export const SKILLS: { icon: typeof Headphones; key: IeltsSkill }[] = [
  { icon: BookOpen,   key: 'reading' },
  { icon: Headphones, key: 'listening' },
  { icon: PenLine,    key: 'writing' },
  { icon: Mic,        key: 'speaking' },
];

export const IELTS_TRANSLATIONS: any = {
  uz: {
    title: 'IELTS Hub',
    join: "Guruhga Qo'shilish",
    subtitleMember: (n: number) => `${n} ta guruhga a'zosiz`,
    subtitleEmpty: "Guruhga qo'shiling yoki mustaqil mashq qiling.",
    tabs: { groups: 'Guruhlarim', practice: 'Amaliyot', progress: "Yo'lim" },
    groups: {
      title: 'Mening guruhlarim',
      subtitle: "O'qituvchi tayinlagan mock testlar shu guruhlar ichida.",
      students: "O'quvchi",
      tip: { before: "Yangi guruhga qo'shilish uchun", link: 'bu yerni bosing', middle: 'va yangi', after: 'kodini kiriting.' },
      emptyTitle: "Hali hech qanday guruh yo'q",
      emptyDesc: "O'qituvchingizdan I-XXXX formatidagi IELTS guruh kodini oling va quyidagi tugmani bosing.",
      emptyPractice: 'Amaliyot kutubxonasini ochish',
      errorTitle: 'Guruhlarni yuklab bo\'lmadi',
      errorDesc: 'Internet aloqasini tekshirib, qayta urinib ko\'ring.',
      errorRetry: 'Qayta urinish',
    },
    practice: {
      title: 'Amaliyot kutubxonasi',
      subtitle: 'Istalgan testni istalgan payt yeching — urinishlar cheklanmagan.',
      practiceBtn: 'Mashq qilish',
      questions: 'savol',
      minutes: 'daqiqa',
      writingInfo: '2 ta vazifa',
      speakingInfo: '3 qism',
      bestBand: 'Eng yaxshi',
      count: (n: number) => `${n} ta test`,
      emptyTitle: "Bu bo'limda hozircha test yo'q",
      emptyDesc: "Tez orada yangi testlar qo'shiladi — keyinroq qaytib ko'ring.",
      loadError: 'Testlarni yuklab bo\'lmadi',
      typeFilterClear: 'Filtrni olib tashlash',
      filteredBy: 'Savol turi bo\'yicha filtr',
    },
    progress: {
      title: 'Mening IELTS yo\'lim',
      subtitle: 'Barcha guruh va mustaqil urinishlaringiz bo\'yicha band dinamikasi.',
      overall: 'Taxminiy umumiy band',
      latest: 'Oxirgi',
      best: 'Eng yaxshi',
      attempts: 'Urinishlar',
      graded: 'Baholangan',
      trend: 'Band dinamikasi',
      emptyTitle: 'Hali baholangan urinish yo\'q',
      emptyDesc: 'Birinchi testni yeching — natijalaringiz shu yerda grafik bo\'lib ko\'rinadi.',
      emptyCta: 'Amaliyotni boshlash',
    },
    skills: { listening: 'Listening', reading: 'Reading', writing: 'Writing', speaking: 'Speaking' },
  },
  en: {
    title: 'IELTS Hub',
    join: 'Join a Group',
    subtitleMember: (n: number) => `You are a member of ${n} ${n === 1 ? 'group' : 'groups'}`,
    subtitleEmpty: 'Join a group or practice on your own.',
    tabs: { groups: 'My groups', practice: 'Practice', progress: 'My journey' },
    groups: {
      title: 'My groups',
      subtitle: 'Mock tests your teacher assigns live inside these groups.',
      students: 'Students',
      tip: { before: 'To join a new group,', link: 'click here', middle: 'and enter a new', after: 'code.' },
      emptyTitle: 'No groups yet',
      emptyDesc: 'Get the I-XXXX IELTS group code from your teacher and press the button below.',
      emptyPractice: 'Open the Practice Library',
      errorTitle: 'Could not load your groups',
      errorDesc: 'Check your connection and try again.',
      errorRetry: 'Try again',
    },
    practice: {
      title: 'Practice Library',
      subtitle: 'Take any test anytime — unlimited retakes.',
      practiceBtn: 'Practice',
      questions: 'questions',
      minutes: 'min',
      writingInfo: '2 tasks',
      speakingInfo: '3 parts',
      bestBand: 'Best',
      count: (n: number) => `${n} ${n === 1 ? 'test' : 'tests'}`,
      emptyTitle: 'No tests in this section yet',
      emptyDesc: 'New tests are coming soon — check back later.',
      loadError: 'Could not load tests',
      typeFilterClear: 'Clear filter',
      filteredBy: 'Filtered by question type',
    },
    progress: {
      title: 'My IELTS journey',
      subtitle: 'Band trajectory across every group and self-practice attempt.',
      overall: 'Estimated overall band',
      latest: 'Latest',
      best: 'Best',
      attempts: 'Attempts',
      graded: 'Graded',
      trend: 'Band trajectory',
      emptyTitle: 'No graded attempts yet',
      emptyDesc: 'Take your first test — your results will show up here as a trend line.',
      emptyCta: 'Start practising',
    },
    skills: { listening: 'Listening', reading: 'Reading', writing: 'Writing', speaking: 'Speaking' },
  },
  ru: {
    title: 'IELTS Hub',
    join: 'Вступить в группу',
    subtitleMember: (n: number) => `Вы состоите в ${n} ${n === 1 ? 'группе' : 'группах'}`,
    subtitleEmpty: 'Вступите в группу или тренируйтесь самостоятельно.',
    tabs: { groups: 'Мои группы', practice: 'Практика', progress: 'Мой путь' },
    groups: {
      title: 'Мои группы',
      subtitle: 'Мок-тесты, которые назначает учитель, находятся внутри этих групп.',
      students: 'Учеников',
      tip: { before: 'Чтобы вступить в новую группу,', link: 'нажмите здесь', middle: 'и введите новый код', after: '' },
      emptyTitle: 'Пока нет ни одной группы',
      emptyDesc: 'Получите у учителя код IELTS группы в формате I-XXXX и нажмите кнопку ниже.',
      emptyPractice: 'Открыть библиотеку практики',
      errorTitle: 'Не удалось загрузить группы',
      errorDesc: 'Проверьте соединение и попробуйте ещё раз.',
      errorRetry: 'Повторить',
    },
    practice: {
      title: 'Библиотека практики',
      subtitle: 'Решайте любой тест в любое время — попытки не ограничены.',
      practiceBtn: 'Практика',
      questions: 'вопросов',
      minutes: 'мин',
      writingInfo: '2 задания',
      speakingInfo: '3 части',
      bestBand: 'Лучший',
      count: (n: number) => `Тестов: ${n}`,
      emptyTitle: 'В этом разделе пока нет тестов',
      emptyDesc: 'Новые тесты скоро появятся — загляните позже.',
      loadError: 'Не удалось загрузить тесты',
      typeFilterClear: 'Сбросить фильтр',
      filteredBy: 'Фильтр по типу вопроса',
    },
    progress: {
      title: 'Мой путь IELTS',
      subtitle: 'Динамика band по всем группам и самостоятельным попыткам.',
      overall: 'Примерный общий балл',
      latest: 'Последний',
      best: 'Лучший',
      attempts: 'Попытки',
      graded: 'Оценено',
      trend: 'Динамика band',
      emptyTitle: 'Оценённых попыток пока нет',
      emptyDesc: 'Пройдите первый тест — результаты появятся здесь в виде графика.',
      emptyCta: 'Начать практику',
    },
    skills: { listening: 'Listening', reading: 'Reading', writing: 'Writing', speaking: 'Speaking' },
  },
};
